### ISSUE TITLE
Problem with Thunderbird 78.4.3 and 78.5.0

### ISSUE THREAD

**Issue by David-A-James** [darktrojan/box#3]
I've used Filelink for Box successfully in the past - I can't remember how long ago I last used it. Tonight I tried using it with Thunderbird 78.4.3 (and then later updated Thunderbird to 78.5.0). 

I can't get Filelink for Box to "Connect your Box account" with Thunderbird.

In Thunderbird | Options | Composition | Attachments, Box has an exclamation mark in a yellow triangle alongside it. If I click on the "Connect your Box account" button, then Box open up in my Browser with "Log in to grant access to Box", I put in my email address and password, and click the "Authorize" button. 

That gets me to a page which says "There seems to be a problem with this app, ... Error: invalid client" 

![Thunderbird_FileLink_for_Box](https://user-images.githubusercontent.com/8606919/99611078-e3833b00-2a0a-11eb-97ea-ac18fb64b262.PNG)

Whatever the state of the arrow by "Show Error Details", no further details are shown.

Any ideas gratefully received ...

**Comment by darktrojan** [comment]
Hmm, that's weird. It's still working, I just set up my account again. Maybe something went wrong on their end.

**Comment by David-A-James** [comment]
I still can't get it to work for me. On the off-chance that it was a problem with my Box account, I've created a new Box account and the behaviour is the same with that.
One thought - both the Box accounts I have tried to use are Free Personal accounts - might this only work with paid accounts now (it certainly worked with a free personal account when I used it in the past)?

**Comment by RBarci** [comment]
I have the same problem with Thunderbird 91.2.0.
I removed the extension and nothing changes. Impossible to click on Connect Your Bob account.
I've also used on the past.

**Comment by darktrojan** [comment]
I still don't know what the original problem is and I think there's a separate issue in 91. But in any case I've just enabled a new version (5) on the add-ons website that does work. Go and get it.

**Comment by David-A-James** [comment]
On 18/10/2021 02:30, Geoff Lankow wrote:
>
> Closed #3 <https://github.com/darktrojan/box/issues/3>.
>
>
Unfortunately, I still see the same problem.

This is with Thunderbird 91.2.1 (32-bit).

I downloaded the xpi for Filelink for Box and installed it into 
Thunderbird today. FileLink for Box (in Extensions, Manage > Details) 
says version 5.

Box says "Error: invalid client" when I click the "Authorize" button 
after entering email address and password on the "Log in to grant access 
to Box" window which appears when I click the "Connect your Box account" 
in Thunderbird > Preferences > Composition > Attachments.

I can successfully log in to Box directly (at 
https://account.box.com/login) using the same email address and password.

Am I doing something stupid?

David

-- 
David James
***@***.***
